pages:
  stage: deploy
  script:
  - mkdir ./public
  - cp -R ./{index.html,style.css,assets,fonts,apple-touch-icon.png,favicon.png,favicon.svg,card.png} ./public
  artifacts:
    paths:
    - public
  only:
  - master
